flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class NewPost(FlaskForm):
    title = StringField('Title',validators = [DataRequired()])
    content = TextAreaField('Content', validators= [DataRequired()])
    submit = SubmitField('Post')

flask_blog/main/routes.py
from flask_login import current_user
from flask import render_template,request,Blueprint,redirect,url_for,flash
from flask_blog.models import Posts
from flask_blog.main.forms import Contact
from flask_blog.models import Contacts
from flask_blog import db
from flask_blog.main.utils import send_feedback_email

main = Blueprint('main',__name__)


@main.route("/")
def home():

    page = request.args.get('page',1,type = int)
    posts = Posts.query.order_by(Posts.date_posted.desc()).paginate(page = page,per_page = 4)
    return render_template('index.html',posts = posts)

@main.route("/about")
def about():
    return render_template('about.html')

@main.route("/contact",methods = ['GET','POST'])
def contact():
    form = Contact()
    if current_user.is_authenticated:
        form.email.data = current_user.email
    if form.validate_on_submit():
        send_feedback_email(form)
        feed = Contacts(email = form.email.data, subject = form.subject.data, content = form.description.data)   
        # with users.app_context():
        db.session.add(feed)
        db.session.commit()
        flash(f'Message Successfully Sent, We will respond you ASAP through the email you have provided','success')
        return redirect(url_for('main.home'))
    return render_template('contact.html',form = form)

flask_blog/posts/routes.py
# from flask import Blueprint
# import secrets
# import os
# from PIL import Image
from flask import render_template,url_for,flash,redirect,request,abort,Blueprint
from flask_blog.posts.forms import NewPost
from flask_blog.models import Posts
from flask_blog import db
# from flask_mail import Message
from flask_login import current_user,login_required

posts = Blueprint('posts',__name__)

@posts.route("/posts/new",methods = ['GET','POST'])
@login_required
def new():
    form = NewPost()
    if form.validate_on_submit():
        post = Posts(title = form.title.data, content = form.content.data, author = current_user)
        # with posts.app_context():
        db.session.add(post)
        db.session.commit()
        flash("Your Post had been added Successfully","success")
        return redirect(url_for("main.home"))
    return render_template('new_post.html',form = form, legend = 'New Post')

@posts.route("/posts/<int:post_id>")
def post(post_id):

    post = Posts.query.get_or_404(post_id)
    return render_template("post.html",post = post)


@posts.route("/posts/<int:post_id>/update",methods = ['GET','POST'])
@login_required
def update_post(post_id):
    post = Posts.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    form = NewPost()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data

        db.session.commit()
        flash("Your Post has been Updated Successfully!",'success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('new_post.html',form = form,legend = 'Update Post')

@posts.route("/posts/<int:post_id>/delete",methods = ['POST'])
@login_required
def delete_post(post_id):
    post = Posts.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your Post has been Deleted Successfully!!",'success')
    return redirect(url_for('main.home'))

flask_blog/users/routes.py
from flask import Blueprint,render_template,url_for,flash,redirect,request
from flask_blog.users.forms import RegistrationForm,LoginForm,AccountUpdateForm,RequestResetForm,ResetPassword
from flask_blog.models import User,Posts
from flask_blog import db, bcrypt
from flask_login import login_user,current_user,logout_user,login_required
from flask_blog.users.utils import send_reset_email,save_picture

users = Blueprint('users',__name__)


@users.route("/register",methods = ['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        # hashing passwords
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        #Inserting Data to site.db
        user = User(username = form.username.data, email = form.email.data, password = hashed_password)   
        # with users.app_context():
        db.session.add(user)
        db.session.commit()

        flash(f'The Account has been Created Successfully!!, You can now Login',category='success')
        return redirect(url_for('users.login'))
    return render_template('register.html',title = 'Register',form = form)


@users.route("/login", methods = ['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        
        if user and bcrypt.check_password_hash(user.password,form.password.data):
        # if form.username.data == 'admin' and form.password.data == 'password':
            login_user(user,remember = form.remember.data)
            next_page = request.args.get('next')
            flash('You are Successfully Logged In!',category='success')
            if next_page:
                return redirect(next_page)
            return redirect(url_for('main.home')) 
        else:
            flash('Login Unsuccessful, Please Check the Username and Password','danger')   
    return render_template('login.html',title = 'Login',form = form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account",methods = ['GET','POST'])
@login_required
def account():
    form = AccountUpdateForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture = save_picture(form.picture.data)
            current_user.image_file = picture
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f"Your Account has been Updated Successfully","success")
        return redirect(url_for("users.account"))
    # elif request.method == 'GET':
        # form.username.data = current_user.username
        # form.email.data = current_user.email
    image_file = url_for('static', filename = f'profile_pics/{current_user.image_file}')
    return render_template('account.html',title = 'Account',image_file = image_file,form = form,user = current_user)


@users.route("/user/<string:username>")
def user_post(username):
    page = request.args.get('page',1,type = int)
    user = User.query.filter_by(username = username).first_or_404()
    posts = Posts.query.filter_by(author = user).\
            order_by(Posts.date_posted.desc()).\
            paginate(page = page,per_page = 4)
    return render_template('user_post.html',posts = posts,user = user)


@users.route("/reset_password",methods = ['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash("A Confirmation Email has been sent to you, Please confirm to continue",'info')
        return redirect(url_for('users.login'))
    return render_template("reset_request.html",form = form)

@users.route("/reset_password/<string:token>",methods = ['GET','POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash("Time Limit Exceeded",'warning')
        return render_template(url_for('users.reset_request'))
    form = ResetPassword()
    if form.validate_on_submit():
    # hashing passwords
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        #changing Password in the Database
        user.password = hashed_password
        db.session.commit()

        flash(f'Your Password has been Successfully Updated',category='success')
        return redirect(url_for('users.login'))
    return render_template("reset_password.html",form = form)

flask_blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
<h1>About Page</h1>
{% endblock content %}

flask_blog/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username}}</h2>
            <p class="text-secondary">{{current_user.email}}</p>
        </div>
    </div>
    <!-- FORM HERE -->
    <form method='POST' action='' enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>

            <div class="form-group mt-3">
                {{ form.username.label(class = "form-control-label mb-2")}}
                {% if form.username.errors %}
                {% for error in form.username.errors %}
                {{ form.username(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.username(class = "form-control form-control-lg", placeholder = user.username)}}
                {% endif %}
            </div>
            <div class="form-group mt-3">
                {{ form.email.label(class = "form-control-label mb-2")}}
                {% if form.email.errors %}
                {% for error in form.email.errors %}
                {{ form.email(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.email(class = "form-control form-control-lg", placeholder = user.email)}}
                {% endif %}
            </div>
            <div class="form-group mt-3">
                {{ form.picture.label(class = "form-control-label mb-2")}}<br>
                {{ form.picture(class = "form-control-file")}}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}<br>
                <span class="text-danger">{{ error }}</span>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group mt-3">
            {{form.submit(class = "btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock %}

flask_blog/templates/contact.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method='POST' action=''>
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Contact Us</legend>

            <div class="form-group mt-3">
                {{ form.email.label(class = "form-control-label mb-2")}}
                {% if form.email.errors %}
                {% for error in form.email.errors %}
                {{ form.email(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.email(class = "form-control form-control-lg")}}
                {% endif %}
            </div>

            <div class="form-group mt-3">
                {{ form.subject.label(class = "form-control-label mb-2")}}
                {% if form.subject.errors %}
                {% for error in form.subject.errors %}
                {{ form.subject(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.subject(class = "form-control form-control-lg")}}
                {% endif %}
            </div>

            <div class="form-group mt-3">
                {{ form.description.label(class = "form-control-label mb-2")}}
                {% if form.description.errors %}
                {% for error in form.description.errors %}
                {{ form.description(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.description(class = "form-control form-control-lg")}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group mt-3 mb-2">
            {{form.submit(class = "btn btn-outline-info")}}
        </div>

    </form>
</div>
{% endblock content %}

flask_blog/templates/index.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts.items %}

<article class="media content-section">
    <div class="heading">
        <img class="rounded-circle article-img"
            src="{{ url_for( 'static' , filename = 'profile_pics/' + post.author.image_file )}}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_post',username = post.author.username) }}">{{
                    post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
        </div>
    </div>
    <div class="body ms-3 mt-2">
        <h2><a class="article-title" href="{{ url_for('posts.post',post_id = post.id) }}">
                {{ post.title }}
            </a></h2>
        <p class="article-content">
            {% if post.content|length > 102 %}
            {{ post.content[0:102] + "....." }}
            {% else %}
            {{ post.content }}
            {% endif %}
        </p>
    </div>
</article>

{% endfor %}
{% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('main.home', page = page_num) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page = page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
....
{% endif %}
{% endfor %}
{% endblock content %}

flask_blog/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WebBlog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/footer.css') }}">
</head>

<body>

    <!-- Navigationn Bar starts Here -->
    <nav class="navbar navbar-expand-lg navbar-light"
        style="background-color: #e6c3eb; position: sticky; top: 0%; z-index: 10;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">
                <img src="{{url_for('static', filename = 'images/logo.png')}}" alt="" width="30" height="24"
                    class="d-inline-block align-text-top">

            </a>
            <a class="navbar-brand" href="{{ url_for('main.home') }}">WebBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                    </li>
                </ul>

                {% if current_user.is_authenticated %}
                <a href="{{ url_for('posts.new') }}"><button type="button" class="btn btn-outline-secondary me-3">New
                        Post</button></a>
                <a href="{{ url_for('users.account') }}"><button type="button"
                        class="btn btn-outline-secondary me-3">Account</button></a>

                <a href="{{ url_for('users.logout') }}"><button type="button"
                        class="btn btn-outline-secondary me-3">Logout</button></a>
                {% else %}
                <a href="{{ url_for('users.login') }}"><button type="button"
                        class="btn btn-outline-secondary me-3">Login</button></a>
                <a href="{{ url_for('users.register') }}"><button type="button"
                        class="btn btn-outline-secondary me-5">Sign
                        Up</button></a>
                {% endif %}
            </div>
        </div>
    </nav>
    <!-- Navigation Bar Ends Here -->

    <!-- SideBar Starts here -->
    <main role="main" class="container mt" style="margin-top: 1rem; min-height: calc(100vh - 16.2vh);">
        <div class=" row">
            <div class="col-md-8">
                {% with message = get_flashed_messages(with_categories = True) %}
                {% if message %}
                {% for category,message in message %}
                <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                <div class="container">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <!-- SideBar Ends here -->

    <!-- footer Starts Here -->
    <footer>
        <div class="copy"> Copyright &copy; 2022 All Rights Reserved</div>
        <ul class="icons">
            <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
            <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
            <li><a href="{{url_for('main.contact')}}"><i class="fa-solid fa-envelope"></i></a></li>
            <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
        </ul>
    </footer>
    <!-- footer Ends Here -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/9683a222f9.js" crossorigin="anonymous"></script>
</body>

</html>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method='POST' action=''>
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>

            <div class="form-group mt-3">
                {{ form.username.label(class = "form-control-label mb-2")}}
                {% if form.username.errors %}
                {% for error in form.username.errors %}
                {{ form.username(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.username(class = "form-control form-control-lg")}}
                {% endif %}
            </div>

            <div class="form-group mt-3">
                {{ form.password.label(class = "form-control-label mb-2")}}
                {% if form.password.errors %}
                {% for error in form.password.errors %}
                {{ form.password(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.password(class = "form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-check mt-2">
                {{ form.remember(class = "form-check-input") }}
                {{ form.remember.label(class = "form-check-label") }}

            </div>
        </fieldset>
        <div class="form-group mt-3 mb-2">
            {{form.submit(class = "btn btn-outline-info")}}
            <small class="text-muted ms-4"><a href="{{ url_for('users.reset_request') }}">Forgot Password?</a></small>
        </div>

    </form>
</div>
<div class='border-bottom pt-3'>
    <small class="text-muted">
        Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
    </small>
</div>
{% endblock content %}

flask_blog/templates/new_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method='POST' action=''>
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <div class="form-group mt-3">
                {{ form.title.label(class = "form-control-label mb-2")}}
                {% if form.title.errors %}
                {% for error in form.title.errors %}
                {{ form.title(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.title(class = "form-control form-control-lg")}}
                {% endif %}
            </div>

            <div class="form-group mt-3">
                {{ form.content.label(class = "form-control-label mb-2")}}
                {% if form.content.errors %}
                {% for error in form.content.errors %}
                {{ form.content(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.content(class = "form-control form-control-lg")}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group mt-3 mb-2">
            {{form.submit(class = "btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <div class="heading">
        <img class="rounded-circle article-img"
            src="{{ url_for( 'static' , filename = 'profile_pics/' + post.author.image_file )}}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_post',username = post.author.username) }}">{{
                    post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                <div>
                    <a href="{{ url_for('posts.update_post',post_id = post.id) }}" class="btn btn-secondary m-1 btn-sm"
                        style="font-size: 1rem;">Update</a>
                    <button class="btn btn-danger m-1" type="button" data-bs-toggle="modal"
                        data-bs-target="#deleteModal">Delete</button>
                </div>
                {% endif%}
            </div>
        </div>
    </div>
    <div class="body m-3">
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>

</article>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form method="post" action="{{ url_for('posts.delete_post',post_id = post.id) }}">
                    <input type="submit" class="btn btn-danger" value="Delete">

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flask_blog/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method='POST' action=''>
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>

            <div class="form-group mt-3">
                {{ form.username.label(class = "form-control-label mb-2")}}
                {% if form.username.errors %}
                {% for error in form.username.errors %}
                {{ form.username(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.username(class = "form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group mt-3">
                {{ form.email.label(class = "form-control-label mb-2")}}
                {% if form.email.errors %}
                {% for error in form.email.errors %}
                {{ form.email(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.email(class = "form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group mt-3">
                {{ form.password.label(class = "form-control-label mb-2")}}
                {% if form.password.errors %}
                {% for error in form.password.errors %}
                {{ form.password(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.password(class = "form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group mt-3">
                {{ form.confirm_password.label(class = "form-control-label mb-2")}}
                {% if form.confirm_password.errors %}
                {% for error in form.confirm_password.errors %}
                {{ form.confirm_password(class = "form-control form-control-lg is-invalid")}}
                <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.confirm_password(class = "form-control form-control-lg")}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group mt-3">
            {{form.submit(class = "btn btn-outline-info")}}
        </div>
    </form>
</div>
<div class='border-bottom pt-3'>
    <small class="text-muted">
        Already have an Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign in</a>
    </small>
</div>
{% endblock content %}

flask_blog/templates/user_post.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3">Posts By {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}

<article class="media content-section">
    <div class="heading">
        <img class="rounded-circle article-img"
            src="{{ url_for( 'static' , filename = 'profile_pics/' + post.author.image_file )}}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_post',username = post.author.username) }}">{{
                    post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
        </div>
    </div>
    <div class="body ms-3 mt-2">
        <h2><a class="article-title" href="{{ url_for('posts.post',post_id = post.id) }}">
                {{ post.title }}
            </a></h2>
        <p class="article-content">
            {% if post.content|length > 102 %}
            {{ post.content[0:102] + "....." }}
            {% else %}
            {{ post.content }}
            {% endif %}
        </p>
    </div>
</article>

{% endfor %}
{% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('users.user_post',username = user.username, page = page_num) }}">{{
    page_num
    }}</a>
{% else %}
<a class="btn btn-outline-info mb-4"
    href="{{ url_for('users.user_post',username = user.username, page = page_num) }}">{{
    page_num }}</a>
{% endif %}
{% else %}
....
{% endif %}
{% endfor %}
{% endblock content %}